server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/projectdb?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1234567
mybatis:
  #  指令Mapper映射文件的位置
  mapper-locations: "classpath:mapper/*Mapper.xml"
  #  配置别名
  type-aliases-package: com.tjetc.entity
logging:
  level:
    com.tjetc: debug